### ISSUE TITLE
Where did 0120000.tar download from?

### ISSUE THREAD

**Issue by FriedaSmith** [memento0ageru1/SD-RSIC#1]
Hello, where did **0120000.tar** download from? Can you provide it?

**Comment by memento0ageru1** [comment]
I changed the project：https://github.com/tzoof/Text-Summarizer-Pytorch, and trained the model 0120000.tar on the kaggle. you can download 0120000.tar in the release of https://github.com/memento0ageru1/Text-Summarizer-Pytorch. But I can't guarantee it's the best model because of the time limit of train on the kaggle.

**Comment by FriedaSmith** [comment]
Thank you very much.
